# AmazingJoin Main Configuration File
# Version: 1.0.1
#
# Thanks for using AmazingJoin!
#
# !!!USEFUL INFO!!!
# Wiki url: https://cubicdev.gitbook.io/amazingjoin
# Modrinth url: https://modrinth.com/project/amazingjoin
#
# This configuration's keys will be restored by themselves if deleted.
# If new configuration keys are added in updates, they will be added automatically here
# when updating the jar file and starting the server.
config:
  debug: false
  hooks:
    authme: false
    nlogin: false
  language:
    prefix: "<gray>[</gray><yellow>AmazingJoin<gray>]</gray>"
    reload_success: "<prefix> <green>AmazingJoin has successfully been reloaded."
    format_not_found: "<prefix> <red>That format was not found in the configuration file."
    format_cannot_be_created: "<prefix> <red>Could not create the format, check for console errors."
    format_doesnt_exist: "<prefix> <red>This format doesn't exist."
    format_created: "<prefix> <green>The format <name> created succesfully, you can now edit it in configuration or using <gold>/amazingjoin addaction."
    format_action_added: "<prefix> <green>Successfuly added the action to the format."
    format_testing_success: "<prefix> <green>Testing the format..."
    help_message:
      - ""
      - "<prefix> <green>Showing help message:"
      - ""
      - "<dark_gray>• <color:#1BCC91>/amazingjoin create <name> <permission> <dark_gray>‣ <white>Creates a new format in config with the parameters specified."
      - ""
      - "<dark_gray>• <color:#1BCC91>/amazingjoin addaction <format_name> <join/leave> <action> <dark_gray>‣ <white>Writes a new action to the specified format configuration."
      - ""
      - "<dark_gray>• <color:#1BCC91>/amazingjoin test <format_name> <join/leave> <dark_gray>‣ <white>Tests the specified format with your own user."
      - ""
      - "<dark_gray>• <color:#1BCC91>/amazingjoin reload <dark_gray>‣ <white>Reloads the configuration."
      - ""
      - "<dark_gray>• <color:#1BCC91>/amazingjoin help <dark_gray>‣ <white>Shows this message."
      - ""
      - "<gray><italic>Need more help?"
      - "<dark_gray>• <white>Wiki: <yellow>https://cubicdev.gitbook.io/amazingjoin"
      - "<dark_gray>• <white>Discord user: <yellow>elsus1719"
      - ""
    new_version_message: "<prefix> <green>A new version of AmazingJoin has been released! Download the new version <gold><version></gold> in <gold>https://modrinth.com/plugin/amazingjoin</gold>."