config:
  debug: true
  language:
    prefix: "<gray>[</gray><yellow>AmazingJoin<gray>]</gray>"
    reload_success: "<prefix> <green>AmazingJoin has successfully been reloaded."
    format_not_found: "<prefix> <red>That format was not found in the configuration file."
    format_cannot_be_created: "<prefix> <red>Could not create the format, check for console errors."
    format_doesnt_exist: "<prefix> <red>This format doesn't exist."
    format_created: "<prefix> <green>The format <name> created succesfully, you can now edit it in configuration or using <gold>/amazingjoin addaction."
    format_action_added: "<prefix> <green>Successfuly added the action to the format."
    format_testing_success: "<prefix> <green>Testing the format..."